const express = require('express');
const cors = require('cors');
const Database = require('better-sqlite3');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

const dbPath = path.resolve(__dirname, 'habits.db');
const db = new Database(dbPath);

// Initialize Tables
db.prepare(`
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'user'
  )
`).run();

db.prepare(`
  CREATE TABLE IF NOT EXISTS events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
  )
`).run();

// Dynamic Schema Migration Check
db.prepare(`
  CREATE TABLE IF NOT EXISTS activities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    event_type TEXT NOT NULL,
    details TEXT,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    duration_seconds INTEGER NOT NULL
  )
`).run();

// Ensure 'user_id' exists if table was generated by older schema
const columns = db.prepare(`PRAGMA table_info(activities)`).all();
const hasUserId = columns.some(col => col.name === 'user_id');
if (!hasUserId) {
  db.prepare(`ALTER TABLE activities ADD COLUMN user_id INTEGER`).run();
}

// Seed Initial Admin & Events
try {
  db.prepare(`INSERT OR IGNORE INTO users (username, password, role) VALUES (?, ?, ?)`).run('jadenseantam', 'Jaden0309', 'admin');
  const seedEvent = db.prepare(`INSERT OR IGNORE INTO events (name) VALUES (?)`);
  ['Homework'].forEach(e => seedEvent.run(e));
} catch (e) {}

// --- ROUTES ---

app.post('/api/auth/register', (req, res) => {
  const { username, password } = req.body;
  if (!username || !password) return res.status(400).json({ message: 'Missing fields.' });
  try {
    const stmt = db.prepare('INSERT INTO users (username, password, role) VALUES (?, ?, ?)');
    const result = stmt.run(username, password, 'user');
    res.status(201).json({ success: true, userId: result.lastInsertRowid, username, role: 'user' });
  } catch (error) {
    res.status(400).json({ message: 'Username already exists.' });
  }
});

app.post('/api/auth/login', (req, res) => {
  const { username, password } = req.body;
  try {
    const user = db.prepare('SELECT * FROM users WHERE username = ? AND password = ?').get(username, password);
    if (user) {
      res.status(200).json({ success: true, userId: user.id, username: user.username, role: user.role });
    } else {
      res.status(401).json({ message: 'Invalid credentials.' });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

app.get('/api/admin/users', (req, res) => {
  try {
    res.status(200).json(db.prepare('SELECT id, username, role FROM users').all());
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

app.get('/api/events', (req, res) => {
  try {
    res.status(200).json(db.prepare('SELECT * FROM events ORDER BY id ASC').all());
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

app.post('/api/admin/events', (req, res) => {
  const { eventName } = req.body;
  try {
    db.prepare('INSERT INTO events (name) VALUES (?)').run(eventName);
    res.status(201).json({ success: true });
  } catch (error) {
    res.status(400).json({ message: 'Event already exists.' });
  }
});

app.get('/api/activities', (req, res) => {
  const { userId } = req.query;
  try {
    const activities = db.prepare('SELECT * FROM activities WHERE user_id = ? ORDER BY id DESC').all(userId);
    res.status(200).json(activities);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

app.post('/api/activities/save', (req, res) => {
  const { userId, eventType, details, startTime, endTime } = req.body;
  
  if (!userId || !eventType) {
    return res.status(400).json({ message: 'Missing user ID or event details.' });
  }

  try {
    const start = new Date(startTime);
    const end = new Date(endTime);
    const durationSeconds = Math.max(1, Math.round((end - start) / 1000));

    const stmt = db.prepare(`
      INSERT INTO activities (user_id, event_type, details, start_time, end_time, duration_seconds)
      VALUES (?, ?, ?, ?, ?, ?)
    `);
    stmt.run(Number(userId), eventType, details || '', startTime, endTime, durationSeconds);
    res.status(200).json({ success: true });
  } catch (error) {
    console.error("Database Save Error:", error.message);
    res.status(500).json({ message: error.message });
  }
});

app.listen(PORT, () => console.log(`🚀 Server listening on http://localhost:${PORT}`));